name: Deploy-Web

on:
  push:
    branches: [ master, build/add-web-release-workflow ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
